"""Add user_id to Task

Revision ID: f8b1d0cbf89b
Revises: 
Create Date: 2025-07-13 11:21:31.836140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8b1d0cbf89b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_task_user_id',       # name of the foreign key constraint
            'user',                  # referenced table
            ['user_id'],             # local column
            ['id']                   # referenced column
        )

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
